(function () {
  const state = document.getElementById('roadmapState'); const tasks = document.getElementById('roadmapTasks'); const form = document.getElementById('roadmapSettings');
  async function api(path, options = {}) { const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers: { ...getAuthHeaders(), ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
  const label = value => value.replaceAll('_', ' ').replace(/\b\w/g, char => char.toUpperCase());
  function render(data) { const roadmap = data.roadmap; document.getElementById('targetDate').value = roadmap.targetDate ? roadmap.targetDate.slice(0, 10) : ''; document.getElementById('roadmapContext').innerHTML = `<strong>${escapeHtml(roadmap.targetRoleTitle || 'No target role')}</strong><div class="small text-muted">${escapeHtml(roadmap.targetCompanyName || 'No target company')} · ${data.context.companyPostingsAnalyzed} posting(s) analyzed</div>`; if (data.message) { state.hidden = false; state.innerHTML = `${escapeHtml(data.message)} <a href="student-profile.html" class="alert-link">Choose a career goal</a>`; } else state.hidden = true; tasks.innerHTML = roadmap.tasks.map((task, index) => `<div class="col-12"><article class="card"><div class="card-body p-4 d-flex flex-column flex-md-row gap-3"><div class="rounded-circle bg-light text-primary fw-bold d-grid align-items-center text-center flex-shrink-0" style="width:42px;height:42px">${index + 1}</div><div class="flex-grow-1"><div class="d-flex flex-wrap justify-content-between gap-2"><h5>${escapeHtml(task.title)}</h5><span class="badge text-bg-light border">${escapeHtml(task.source.replaceAll('_', ' '))}</span></div><p class="mb-2">${escapeHtml(task.description)}</p><p class="small text-muted mb-0"><strong>Why:</strong> ${escapeHtml(task.evidence)}</p></div><div class="flex-shrink-0"><label class="visually-hidden" for="status-${task._id}">Task status</label><select class="form-select" id="status-${task._id}" data-task="${task._id}"><option value="NOT_STARTED" ${task.status === 'NOT_STARTED' ? 'selected' : ''}>Not started</option><option value="IN_PROGRESS" ${task.status === 'IN_PROGRESS' ? 'selected' : ''}>In progress</option><option value="COMPLETED" ${task.status === 'COMPLETED' ? 'selected' : ''}>Completed</option></select></div></div></article></div>`).join(''); }
  async function load() { state.hidden = false; state.className = 'alert alert-light border'; state.textContent = 'Loading your roadmap...'; try { render(await api('/students/me/career-roadmap')); } catch (error) { state.className = 'alert alert-danger'; state.innerHTML = `${escapeHtml(error.message)} <button class="btn btn-sm btn-outline-danger ms-2" id="retryRoadmap">Try again</button>`; } }
  form.addEventListener('submit', async event => { event.preventDefault(); const button=document.getElementById('saveTargetDate'); button.disabled=true; button.textContent='Saving...'; try { await api('/students/me/career-roadmap/settings',{method:'PUT',body:JSON.stringify({targetDate:document.getElementById('targetDate').value||null})}); showSuccess('Target date saved successfully'); await load(); } catch(error){showError(error.message);} finally{button.disabled=false;button.textContent='Save target date';} });
  document.addEventListener('change', async event => { const select=event.target.closest('[data-task]'); if(!select)return; select.disabled=true; try{await api(`/students/me/career-roadmap/tasks/${select.dataset.task}`,{method:'PATCH',body:JSON.stringify({status:select.value})});showSuccess(`Task marked ${label(select.value)}`);}catch(error){showError(error.message);await load();}finally{select.disabled=false;} });
  document.addEventListener('click', event => { if(event.target.id==='retryRoadmap')load(); }); load();
})();
