(function () {
  const state = document.getElementById('jobState'); const grid = document.getElementById('jobGrid'); const modal = new bootstrap.Modal(document.getElementById('jobModal'));
  const safeUrl = value => { try { const url = new URL(value); return ['http:', 'https:'].includes(url.protocol) ? url.href : null; } catch { return null; } };
  const badges = (items, tone) => items.length ? items.map(item => `<span class="badge text-bg-${tone} me-1 mb-1">${escapeHtml(item.name)}</span>`).join('') : '<span class="text-muted">None</span>';
  async function api(path, options = {}) { const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers: { ...getAuthHeaders(), ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
  function card(job) {
    const link = safeUrl(job.sourceUrl); const percent = job.comparison.skillMatchPercentage; const why = [...(job.structuredReasons || []), ...(job.comparison.reasons || [])];
    return `<div class="col-lg-6"><article class="card h-100"><div class="card-body p-4"><h4>${escapeHtml(job.title)}</h4><div class="text-muted">${escapeHtml(job.companyName)} · ${escapeHtml(job.location || 'Location not specified')}</div><span class="badge ${job.sourceType === 'employer-provided' ? 'text-bg-success' : 'text-bg-primary'}">${escapeHtml(job.sourceType === 'employer-provided' ? 'Employer provided' : 'Externally observed')}</span><div class="display-6 fw-bold mt-3">${percent === null ? 'N/A' : `${percent}%`}</div><div class="small text-muted">Explicit skill alignment · recommendation ${job.recommendationScore}%</div><div class="mt-3">${badges(job.comparison.matchedSkills, 'success')}</div><details class="small my-3"><summary class="text-primary fw-semibold">Why am I seeing this?</summary><ul class="mt-2">${why.map(item => `<li><strong>${escapeHtml(item.source.replaceAll('_', ' '))}:</strong> ${escapeHtml(item.evidence)}</li>`).join('') || '<li>No personalized reason is available yet.</li>'}</ul></details><div class="d-flex flex-wrap gap-2"><button class="btn btn-primary btn-sm" data-details="${job._id}">View comparison</button><button class="btn btn-outline-primary btn-sm" data-status="saved" data-id="${job._id}">Save</button>${link ? `<a class="btn btn-outline-secondary btn-sm" href="${escapeHtml(link)}" target="_blank" rel="noopener noreferrer">Source</a>` : ''}</div></div></article></div>`;
  }
  async function load() { try { const data = await api('/jobs/recommended/me'); state.hidden = true; if (!data.recommendations.length) { state.hidden = false; state.textContent = 'No active sourced postings are available right now.'; return; } grid.innerHTML = data.recommendations.map(card).join(''); window.jobs = new Map(data.recommendations.map(job => [job._id, job])); } catch (error) { state.className = 'alert alert-danger'; state.textContent = error.message; } }
  document.addEventListener('click', async event => {
    const detail = event.target.closest('[data-details]'); if (detail) { const job = window.jobs.get(detail.dataset.details); document.getElementById('jobModalTitle').textContent = `${job.title} at ${job.companyName}`; const source = safeUrl(job.sourceUrl); document.getElementById('jobModalBody').innerHTML = `<h6>Matched skills</h6>${badges(job.comparison.matchedSkills, 'success')}<h6 class="mt-4">Missing observed skills</h6>${badges(job.comparison.missingSkills, 'warning')}<h6 class="mt-4">Education evidence from posting</h6>${job.comparison.educationRequirements.length ? job.comparison.educationRequirements.map(x => `<p>${escapeHtml(x.sourceText)}</p>`).join('') : '<p class="text-muted">Not specified by source.</p>'}<h6>Experience evidence from posting</h6>${job.comparison.experienceRequirements.length ? job.comparison.experienceRequirements.map(x => `<p>${escapeHtml(x.sourceText)}</p>`).join('') : '<p class="text-muted">Not specified by source.</p>'}${source ? `<a href="${escapeHtml(source)}" target="_blank" rel="noopener noreferrer">Verify on ${escapeHtml(job.sourceName)}</a>` : ''}`; modal.show(); }
    const action = event.target.closest('[data-status]'); if (action) { try { await api(`/jobs/${action.dataset.id}/activity`, { method: 'PUT', body: JSON.stringify({ status: action.dataset.status }) }); action.textContent = 'Saved'; action.disabled = true; } catch (error) { showError(error.message); } }
  }); load();
})();
